title: Rinoy R K
# logo: /assets/img/logo.png
description: Full stack developer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

